apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elasticsearch
spec:
  version: 8.2.2
  count: 2
  elasticsearchRef:
    name: elasticsearch
  http:
    tls: 
      selfSignedCertificate:
        disabled: true