global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
 - /etc/prometheus/rules.yml

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090', 'ec2-3-229-37-74.compute-1.amazonaws.com:9100']